### PR TITLE
Add metadata

### PR DESCRIPTION
**Pull request by dominikl**
Add the necessary files for import and annotations.

Includes @francesw 's changes from #4

### CODE REVIEW

**Comment by dominikl** [comment]
Included @francesw changes of #2 into this PR.

**Comment by dominikl** [comment]
Included #4. Had to do it manually because #4's csv files contain some weird unicode characters.

**Comment by dominikl** [comment]
Can we turn of `yamllint` for travis please? I can't break the URL values like `https://www.ncbi.nlm.nih.gov/gene/?term={{ value|urlencode }}` over multiple lines.

**Comment by sbesson** [comment]
@dominikl: found out that the way to break long lines in YAML is to use `\` e.g. https://github.com/ome/ansible-role-omero-web-apps/blob/0.2.0/tasks/main.yml#L18. 
An alternative to turning `yamllint` off completely would be to add a top-level `.yamllint` increasing the maximum line length. Optionally we could also disable the truthy check to support `yes/no`

```
extends: default

rules:
  line-length:
    max: 120
    level: error
  truthy: disable
```

**Comment by dominikl** [comment]
This PR includes all @francesw 's changes of #4 . Once this PR is merged, #4 can be closed.

**Comment by joshmoore** [comment]
Screen Shot 2020-01-14 at 13 47 26
Nice :+1:

**Pull request merged**
